#print("5*6")
#print('5*6')
#print(5*6)
#print("Hello World")
#print("Hello World"")
#print("Hello\"")
#print("Hello\nWorld")
#print("Hello\tWorld")
#print("Hello\World")
#print("Hello\\World")
print("Hello'World")